linters:
  disable-all: true
  enable:
    - misspell
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    
issues:
  # We want to make sure we get a full report every time. Setting these
  # to zero disables the limit.
  max-issues-per-linter: 0
  max-same-issues: 0
  
# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 10
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 2m
