apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aws-account-operator
  name: aws-account-shredder
  labels:
    name: aws-account-shredder
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-account-shredder
  template:
    metadata:
      labels:
        name: aws-account-shredder
    spec:
      serviceAccountName: aws-account-shredder
      containers:
        - name: aws-account-shredder
          image: quay.io/app-sre/aws-account-shredder:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "2048Mi"
          env:
            - name : OPERATOR_NAME
              value: "aws-account-shredder"
          ports:
            - containerPort: 8080
